import 'package:spade/models/user.dart';

import '../models/post.dart';
import '../models/story.dart';

User currentUser = User('id', 'stackedList', 'assets/images/Image 40.png');

final List<Story> stories = [
  Story("id", currentUser),
  Story("id", currentUser),
  Story("id", currentUser),
  Story("id", currentUser),
  Story("id", currentUser),
  Story("id", currentUser),
  Story("id", currentUser),
  Story("id", currentUser),
  Story("id", currentUser),
];

final List<Post> posts = [
  Post(
    "id",
    currentUser,
    "title",
    "caption",
    "10 minutes ago",
    "800",
    true,
    false,
    "assets/images/Rectangle 3302 (1).png",
    "South Africa",
  ),
  Post(
    "id1",
    currentUser,
    "title",
    "caption",
    "10 minutes ago",
    "800",
    true,
    false,
    "assets/images/Rectangle 3302 (1).png",
    "Usa american",
  ),
  Post(
    "id2",
    currentUser,
    "title",
    "caption",
    "10 minutes ago",
    "800",
    true,
    false,
    "assets/images/Rectangle 3302 (1).png",
    "Usa american",
  ),
  Post(
    "id3",
    currentUser,
    "title",
    "caption",
    "2 minutes ago",
    "800",
    true,
    false,
    "assets/images/Rectangle 3302 (1).png",
    "Cameroon",
  ),
  Post(
    "id4",
    currentUser,
    "title",
    "caption",
    "10 minutes ago",
    "800",
    true,
    false,
    "assets/images/Rectangle 3302 (1).png",
    "Nigeria",
  ),
  Post(
    "id5",
    currentUser,
    "title",
    "caption",
    "10 minutes ago",
    "800",
    true,
    false,
    "assets/images/Rectangle 3302 (1).png",
    "Usa american",
  ),
  Post(
    "id6",
    currentUser,
    "title",
    "caption",
    "10 minutes ago",
    "800",
    true,
    false,
    "assets/images/Rectangle 3302 (1).png",
    "Usa american",
  ),
];
